ALTER TABLE "ScanLog" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "ScanLog" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "ScanLog" ADD COLUMN IF NOT EXISTS "accuracy" DOUBLE PRECISION;
ALTER TABLE "ScanLog" ADD COLUMN IF NOT EXISTS "locationCapturedAt" TIMESTAMP(3);
